name: Deploy Forensic Scanner

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        # We delete the lockfile here to prevent ARM/x64 conflicts
        run: |
          rm -f package-lock.json
          npm install --legacy-peer-deps

      - name: Build
        run: npm run build
        env:
          # VITE_ prefix is MANDATORY for the frontend to see the secret
          VITE_FIREBASE_CONFIG: ${{ secrets.VITE_FIREBASE_CONFIG }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
